services:
  postgres:
    image: postgres:17.4-alpine
    container_name: postgres-dev
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data:
